//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClothesEntities : DbContext
    {
        public ClothesEntities()
            : base("name=ClothesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImportCoupon> ImportCoupons { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<InvoiceStatu> InvoiceStatus { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSizeColor> ProductSizeColors { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ImportCouponDetail> ImportCouponDetails { get; set; }
    
        public virtual ObjectResult<Nullable<int>> ChangePassword(Nullable<int> userId, string oldPass, string newPass)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var oldPassParameter = oldPass != null ?
                new ObjectParameter("oldPass", oldPass) :
                new ObjectParameter("oldPass", typeof(string));
    
            var newPassParameter = newPass != null ?
                new ObjectParameter("newPass", newPass) :
                new ObjectParameter("newPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ChangePassword", userIdParameter, oldPassParameter, newPassParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DelAccount(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DelAccount", userIdParameter);
        }
    
        public virtual ObjectResult<getCategoryByGender_Result1> getCategoryByGender(Nullable<int> genderID)
        {
            var genderIDParameter = genderID.HasValue ?
                new ObjectParameter("GenderID", genderID) :
                new ObjectParameter("GenderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCategoryByGender_Result1>("getCategoryByGender", genderIDParameter);
        }
    
        public virtual ObjectResult<getCategoryGender_Result1> getCategoryGender(Nullable<int> genderID)
        {
            var genderIDParameter = genderID.HasValue ?
                new ObjectParameter("GenderID", genderID) :
                new ObjectParameter("GenderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCategoryGender_Result1>("getCategoryGender", genderIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_AddOrder(Nullable<int> userId, string address, string phone, string name, string note, string payment, Nullable<int> isPaid)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            var paymentParameter = payment != null ?
                new ObjectParameter("payment", payment) :
                new ObjectParameter("payment", typeof(string));
    
            var isPaidParameter = isPaid.HasValue ?
                new ObjectParameter("isPaid", isPaid) :
                new ObjectParameter("isPaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_AddOrder", userIdParameter, addressParameter, phoneParameter, nameParameter, noteParameter, paymentParameter, isPaidParameter);
        }
    
        public virtual int SP_AddOrderItem(Nullable<int> invoiceId, Nullable<int> productId, Nullable<int> colorId, Nullable<int> sizeId, Nullable<int> quantity)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("invoiceId", invoiceId) :
                new ObjectParameter("invoiceId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            var colorIdParameter = colorId.HasValue ?
                new ObjectParameter("colorId", colorId) :
                new ObjectParameter("colorId", typeof(int));
    
            var sizeIdParameter = sizeId.HasValue ?
                new ObjectParameter("sizeId", sizeId) :
                new ObjectParameter("sizeId", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AddOrderItem", invoiceIdParameter, productIdParameter, colorIdParameter, sizeIdParameter, quantityParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CheckFavoriteProduct(Nullable<int> accountId, Nullable<int> productId)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CheckFavoriteProduct", accountIdParameter, productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CheckUserExist(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CheckUserExist", userIDParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_GetAllAddress_Result2> SP_GetAllAddress(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllAddress_Result2>("SP_GetAllAddress", userIdParameter);
        }
    
        public virtual ObjectResult<SP_GetColorsOfProduct_Result> SP_GetColorsOfProduct(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetColorsOfProduct_Result>("SP_GetColorsOfProduct", productIdParameter);
        }
    
        public virtual ObjectResult<SP_GetFavoriteProducts_Result1> SP_GetFavoriteProducts(Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID)
        {
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetFavoriteProducts_Result1>("SP_GetFavoriteProducts", currentPageParameter, pageSizeParameter, accountIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetFavoriteProductsCount(Nullable<int> accountId)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetFavoriteProductsCount", accountIdParameter);
        }
    
        public virtual ObjectResult<ProductDetail> SP_GetProductInfo(Nullable<int> productID, Nullable<int> accountID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductDetail>("SP_GetProductInfo", productIDParameter, accountIDParameter);
        }
    
        public virtual ObjectResult<SP_GetProductInfoDetail_Result1> SP_GetProductInfoDetail(Nullable<int> productID, Nullable<int> accountID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductInfoDetail_Result1>("SP_GetProductInfoDetail", productIDParameter, accountIDParameter);
        }
    
        public virtual ObjectResult<SP_GetProductOfCategory_Result1> SP_GetProductOfCategory(Nullable<int> categoryId, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID, Nullable<int> sortBy)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            var sortByParameter = sortBy.HasValue ?
                new ObjectParameter("sortBy", sortBy) :
                new ObjectParameter("sortBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductOfCategory_Result1>("SP_GetProductOfCategory", categoryIdParameter, currentPageParameter, pageSizeParameter, accountIDParameter, sortByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetProductOfCategoryCount(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetProductOfCategoryCount", categoryIdParameter);
        }
    
        public virtual ObjectResult<SP_GetProductOfCategory_Result1> SP_GetProductsOfProvider(Nullable<int> providerId, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID, Nullable<int> sortBy)
        {
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            var sortByParameter = sortBy.HasValue ?
                new ObjectParameter("sortBy", sortBy) :
                new ObjectParameter("sortBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductOfCategory_Result1>("SP_GetProductsOfProvider", providerIdParameter, currentPageParameter, pageSizeParameter, accountIDParameter, sortByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetProductsOfProviderCount(Nullable<int> provderId)
        {
            var provderIdParameter = provderId.HasValue ?
                new ObjectParameter("provderId", provderId) :
                new ObjectParameter("provderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetProductsOfProviderCount", provderIdParameter);
        }
    
        public virtual ObjectResult<SP_GetProviderDetail_Result1> SP_GetProviderDetail(Nullable<int> providerId)
        {
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProviderDetail_Result1>("SP_GetProviderDetail", providerIdParameter);
        }
    
        public virtual ObjectResult<SP_GetProviders_Result> SP_GetProviders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProviders_Result>("SP_GetProviders");
        }
    
        public virtual ObjectResult<SP_GetSizesColorsOfProduct_Result> SP_GetSizesColorsOfProduct(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSizesColorsOfProduct_Result>("SP_GetSizesColorsOfProduct", productIdParameter);
        }
    
        public virtual ObjectResult<SP_GetSizesOfProduct_Result> SP_GetSizesOfProduct(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSizesOfProduct_Result>("SP_GetSizesOfProduct", productIdParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<string> SP_ImagesOfProduct(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ImagesOfProduct", productIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Login(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Login", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Register(string name, string email, string phone, Nullable<int> roleId, string password, string username, string imageUrl, Nullable<int> active)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var imageUrlParameter = imageUrl != null ?
                new ObjectParameter("imageUrl", imageUrl) :
                new ObjectParameter("imageUrl", typeof(string));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Register", nameParameter, emailParameter, phoneParameter, roleIdParameter, passwordParameter, usernameParameter, imageUrlParameter, activeParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_UpdateAccInfo(Nullable<int> userId, string name, string phone, string email)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_UpdateAccInfo", userIdParameter, nameParameter, phoneParameter, emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_UpdateUser(Nullable<int> userId, string name, string email, string phone, Nullable<int> roleId, string password, string imageUrl)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var imageUrlParameter = imageUrl != null ?
                new ObjectParameter("imageUrl", imageUrl) :
                new ObjectParameter("imageUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_UpdateUser", userIdParameter, nameParameter, emailParameter, phoneParameter, roleIdParameter, passwordParameter, imageUrlParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SPGetAccounByUsername_Result> SPGetAccounByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetAccounByUsername_Result>("SPGetAccounByUsername", usernameParameter);
        }
    
        public virtual ObjectResult<SPGetAccount_Result> SPGetAccount(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetAccount_Result>("SPGetAccount", userIdParameter);
        }
    
        public virtual ObjectResult<SPGetAccountInfoByUserId_Result1> SPGetAccountInfoByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetAccountInfoByUserId_Result1>("SPGetAccountInfoByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<SPGetAccountInfoByUsername_Result1> SPGetAccountInfoByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetAccountInfoByUsername_Result1>("SPGetAccountInfoByUsername", usernameParameter);
        }
    
        public virtual ObjectResult<SPGetAccountInfoUserID_Result1> SPGetAccountInfoUserID(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetAccountInfoUserID_Result1>("SPGetAccountInfoUserID", userIdParameter);
        }
    
        public virtual ObjectResult<string> SP_GetEmail(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetEmail", userIdParameter);
        }
    
        public virtual ObjectResult<SP_GetAllInvoice_Result1> SP_GetAllInvoice(Nullable<int> statusId, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID)
        {
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllInvoice_Result1>("SP_GetAllInvoice", statusIdParameter, currentPageParameter, pageSizeParameter, accountIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetAllInvoiceCount(Nullable<int> statusId, Nullable<int> accountID)
        {
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetAllInvoiceCount", statusIdParameter, accountIDParameter);
        }
    
        public virtual ObjectResult<SP_GetInvoiceDetail_Result1> SP_GetInvoiceDetail(Nullable<int> inovoiceId)
        {
            var inovoiceIdParameter = inovoiceId.HasValue ?
                new ObjectParameter("inovoiceId", inovoiceId) :
                new ObjectParameter("inovoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetInvoiceDetail_Result1>("SP_GetInvoiceDetail", inovoiceIdParameter);
        }
    
        public virtual ObjectResult<SP_GetProductInvoice_Result2> SP_GetProductInvoice(Nullable<int> inovoiceId)
        {
            var inovoiceIdParameter = inovoiceId.HasValue ?
                new ObjectParameter("inovoiceId", inovoiceId) :
                new ObjectParameter("inovoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductInvoice_Result2>("SP_GetProductInvoice", inovoiceIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CheckInvoiceExist(Nullable<int> inovoiceId)
        {
            var inovoiceIdParameter = inovoiceId.HasValue ?
                new ObjectParameter("inovoiceId", inovoiceId) :
                new ObjectParameter("inovoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CheckInvoiceExist", inovoiceIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_AddAddress(Nullable<int> userId, string province, string district, string wards, string street, string name, string phone, Nullable<int> isDefault)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var provinceParameter = province != null ?
                new ObjectParameter("province", province) :
                new ObjectParameter("province", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("district", district) :
                new ObjectParameter("district", typeof(string));
    
            var wardsParameter = wards != null ?
                new ObjectParameter("wards", wards) :
                new ObjectParameter("wards", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("isDefault", isDefault) :
                new ObjectParameter("isDefault", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_AddAddress", userIdParameter, provinceParameter, districtParameter, wardsParameter, streetParameter, nameParameter, phoneParameter, isDefaultParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_DelAddress(Nullable<int> addressId)
        {
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("addressId", addressId) :
                new ObjectParameter("addressId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DelAddress", addressIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_AddAccount(string firstName, string lastName, string phone, string address, string dateBegin, string birthday, Nullable<int> isWorking, string email, Nullable<int> roleId, string password, string username)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var dateBeginParameter = dateBegin != null ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(string));
    
            var birthdayParameter = birthday != null ?
                new ObjectParameter("birthday", birthday) :
                new ObjectParameter("birthday", typeof(string));
    
            var isWorkingParameter = isWorking.HasValue ?
                new ObjectParameter("isWorking", isWorking) :
                new ObjectParameter("isWorking", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_AddAccount", firstNameParameter, lastNameParameter, phoneParameter, addressParameter, dateBeginParameter, birthdayParameter, isWorkingParameter, emailParameter, roleIdParameter, passwordParameter, usernameParameter);
        }
    
        public virtual int SP_EditAddress(Nullable<int> addressId, string province, string district, string wards, string street, string name, string phone, Nullable<int> isDefault, Nullable<int> accountId)
        {
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("addressId", addressId) :
                new ObjectParameter("addressId", typeof(int));
    
            var provinceParameter = province != null ?
                new ObjectParameter("province", province) :
                new ObjectParameter("province", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("district", district) :
                new ObjectParameter("district", typeof(string));
    
            var wardsParameter = wards != null ?
                new ObjectParameter("wards", wards) :
                new ObjectParameter("wards", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("isDefault", isDefault) :
                new ObjectParameter("isDefault", typeof(int));
    
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EditAddress", addressIdParameter, provinceParameter, districtParameter, wardsParameter, streetParameter, nameParameter, phoneParameter, isDefaultParameter, accountIdParameter);
        }
    
        public virtual int forgotPasswordReset(string email, string newPass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var newPassParameter = newPass != null ?
                new ObjectParameter("newPass", newPass) :
                new ObjectParameter("newPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("forgotPasswordReset", emailParameter, newPassParameter);
        }
    
        public virtual ObjectResult<SP_GetProductOfCategory_Result1> SP_GetProductSearchFilter(Nullable<int> typeId, string keySearch, Nullable<int> typeFilter, Nullable<int> categoryId, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID)
        {
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("typeId", typeId) :
                new ObjectParameter("typeId", typeof(int));
    
            var keySearchParameter = keySearch != null ?
                new ObjectParameter("keySearch", keySearch) :
                new ObjectParameter("keySearch", typeof(string));
    
            var typeFilterParameter = typeFilter.HasValue ?
                new ObjectParameter("typeFilter", typeFilter) :
                new ObjectParameter("typeFilter", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductOfCategory_Result1>("SP_GetProductSearchFilter", typeIdParameter, keySearchParameter, typeFilterParameter, categoryIdParameter, currentPageParameter, pageSizeParameter, accountIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetProductSearchFilterCount(Nullable<int> typeId, string keySearch, Nullable<int> categoryId)
        {
            var typeIdParameter = typeId.HasValue ?
                new ObjectParameter("typeId", typeId) :
                new ObjectParameter("typeId", typeof(int));
    
            var keySearchParameter = keySearch != null ?
                new ObjectParameter("keySearch", keySearch) :
                new ObjectParameter("keySearch", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetProductSearchFilterCount", typeIdParameter, keySearchParameter, categoryIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_AuthAccount(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_AuthAccount", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Sp_GetPriceInvoice(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("orderID", orderID) :
                new ObjectParameter("orderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Sp_GetPriceInvoice", orderIDParameter);
        }
    
        public virtual ObjectResult<SP_GetProductColorSize_Result> SP_GetProductColorSize(Nullable<int> categoryId, Nullable<int> providerId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductColorSize_Result>("SP_GetProductColorSize", categoryIdParameter, providerIdParameter);
        }
    
        public virtual ObjectResult<SP_GetProductOfCategory_Result1> SP_GetProductOfCategoryFilter(Nullable<int> categoryId, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID, Nullable<int> sortBy)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            var sortByParameter = sortBy.HasValue ?
                new ObjectParameter("sortBy", sortBy) :
                new ObjectParameter("sortBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductOfCategory_Result1>("SP_GetProductOfCategoryFilter", categoryIdParameter, currentPageParameter, pageSizeParameter, accountIDParameter, sortByParameter);
        }
    
        public virtual ObjectResult<SP_GetProductOfCategory_Result1> SP_GetProductsOfProviderFilter(Nullable<int> providerId, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID, Nullable<int> sortBy)
        {
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("providerId", providerId) :
                new ObjectParameter("providerId", typeof(int));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            var sortByParameter = sortBy.HasValue ?
                new ObjectParameter("sortBy", sortBy) :
                new ObjectParameter("sortBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductOfCategory_Result1>("SP_GetProductsOfProviderFilter", providerIdParameter, currentPageParameter, pageSizeParameter, accountIDParameter, sortByParameter);
        }
    
        public virtual ObjectResult<SP_GetProductOfCategory_Result1> SP_SearchFilter(string keySearch, Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> accountID, Nullable<int> sortBy)
        {
            var keySearchParameter = keySearch != null ?
                new ObjectParameter("keySearch", keySearch) :
                new ObjectParameter("keySearch", typeof(string));
    
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(int));
    
            var sortByParameter = sortBy.HasValue ?
                new ObjectParameter("sortBy", sortBy) :
                new ObjectParameter("sortBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetProductOfCategory_Result1>("SP_SearchFilter", keySearchParameter, currentPageParameter, pageSizeParameter, accountIDParameter, sortByParameter);
        }
    
        public virtual int SP_SearchFilterCount(string keySearch)
        {
            var keySearchParameter = keySearch != null ?
                new ObjectParameter("keySearch", keySearch) :
                new ObjectParameter("keySearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SearchFilterCount", keySearchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SearchFilterCounter(string keySearch)
        {
            var keySearchParameter = keySearch != null ?
                new ObjectParameter("keySearch", keySearch) :
                new ObjectParameter("keySearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SearchFilterCounter", keySearchParameter);
        }
    
        public virtual ObjectResult<SP_GetRatings_Result6> SP_GetRatings(Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> productId)
        {
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRatings_Result6>("SP_GetRatings", currentPageParameter, pageSizeParameter, productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetRatingsCount(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetRatingsCount", productIdParameter);
        }
    
        public virtual ObjectResult<SP_GetSubRating_Result2> SP_GetSubRating(Nullable<int> ratingId)
        {
            var ratingIdParameter = ratingId.HasValue ?
                new ObjectParameter("ratingId", ratingId) :
                new ObjectParameter("ratingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSubRating_Result2>("SP_GetSubRating", ratingIdParameter);
        }
    
        public virtual int SP_AddRating(Nullable<int> accountId, Nullable<int> rating, string comment, Nullable<int> productID, Nullable<int> orderId, Nullable<int> colorId, Nullable<int> sizeId, string imageUrl1, string imageUrl2, string imageUrl3, string videoUrl, Nullable<int> parentId)
        {
            var accountIdParameter = accountId.HasValue ?
                new ObjectParameter("accountId", accountId) :
                new ObjectParameter("accountId", typeof(int));
    
            var ratingParameter = rating.HasValue ?
                new ObjectParameter("rating", rating) :
                new ObjectParameter("rating", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            var colorIdParameter = colorId.HasValue ?
                new ObjectParameter("colorId", colorId) :
                new ObjectParameter("colorId", typeof(int));
    
            var sizeIdParameter = sizeId.HasValue ?
                new ObjectParameter("sizeId", sizeId) :
                new ObjectParameter("sizeId", typeof(int));
    
            var imageUrl1Parameter = imageUrl1 != null ?
                new ObjectParameter("imageUrl1", imageUrl1) :
                new ObjectParameter("imageUrl1", typeof(string));
    
            var imageUrl2Parameter = imageUrl2 != null ?
                new ObjectParameter("imageUrl2", imageUrl2) :
                new ObjectParameter("imageUrl2", typeof(string));
    
            var imageUrl3Parameter = imageUrl3 != null ?
                new ObjectParameter("imageUrl3", imageUrl3) :
                new ObjectParameter("imageUrl3", typeof(string));
    
            var videoUrlParameter = videoUrl != null ?
                new ObjectParameter("videoUrl", videoUrl) :
                new ObjectParameter("videoUrl", typeof(string));
    
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("parentId", parentId) :
                new ObjectParameter("parentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AddRating", accountIdParameter, ratingParameter, commentParameter, productIDParameter, orderIdParameter, colorIdParameter, sizeIdParameter, imageUrl1Parameter, imageUrl2Parameter, imageUrl3Parameter, videoUrlParameter, parentIdParameter);
        }
    
        public virtual int SP_UpdateRating(Nullable<int> ratingId, Nullable<int> rating, string comment, string imageUrl1, string imageUrl2, string imageUrl3, string videoUrl, Nullable<int> parentId)
        {
            var ratingIdParameter = ratingId.HasValue ?
                new ObjectParameter("ratingId", ratingId) :
                new ObjectParameter("ratingId", typeof(int));
    
            var ratingParameter = rating.HasValue ?
                new ObjectParameter("rating", rating) :
                new ObjectParameter("rating", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var imageUrl1Parameter = imageUrl1 != null ?
                new ObjectParameter("imageUrl1", imageUrl1) :
                new ObjectParameter("imageUrl1", typeof(string));
    
            var imageUrl2Parameter = imageUrl2 != null ?
                new ObjectParameter("imageUrl2", imageUrl2) :
                new ObjectParameter("imageUrl2", typeof(string));
    
            var imageUrl3Parameter = imageUrl3 != null ?
                new ObjectParameter("imageUrl3", imageUrl3) :
                new ObjectParameter("imageUrl3", typeof(string));
    
            var videoUrlParameter = videoUrl != null ?
                new ObjectParameter("videoUrl", videoUrl) :
                new ObjectParameter("videoUrl", typeof(string));
    
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("parentId", parentId) :
                new ObjectParameter("parentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateRating", ratingIdParameter, ratingParameter, commentParameter, imageUrl1Parameter, imageUrl2Parameter, imageUrl3Parameter, videoUrlParameter, parentIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_DelRating(Nullable<int> ratingId)
        {
            var ratingIdParameter = ratingId.HasValue ?
                new ObjectParameter("ratingId", ratingId) :
                new ObjectParameter("ratingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DelRating", ratingIdParameter);
        }
    
        public virtual int SP_AddQuestion(Nullable<int> accountID, string question, Nullable<int> parentQuestionID, Nullable<int> productID)
        {
            var accountIDParameter = accountID.HasValue ?
                new ObjectParameter("accountID", accountID) :
                new ObjectParameter("accountID", typeof(int));
    
            var questionParameter = question != null ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(string));
    
            var parentQuestionIDParameter = parentQuestionID.HasValue ?
                new ObjectParameter("parentQuestionID", parentQuestionID) :
                new ObjectParameter("parentQuestionID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AddQuestion", accountIDParameter, questionParameter, parentQuestionIDParameter, productIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_DelQuestion(Nullable<int> questionId, Nullable<int> isSubQuestion)
        {
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("questionId", questionId) :
                new ObjectParameter("questionId", typeof(int));
    
            var isSubQuestionParameter = isSubQuestion.HasValue ?
                new ObjectParameter("isSubQuestion", isSubQuestion) :
                new ObjectParameter("isSubQuestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_DelQuestion", questionIdParameter, isSubQuestionParameter);
        }
    
        public virtual ObjectResult<SP_GetQuestion_Result1> SP_GetQuestion(Nullable<int> currentPage, Nullable<int> pageSize, Nullable<int> productId)
        {
            var currentPageParameter = currentPage.HasValue ?
                new ObjectParameter("currentPage", currentPage) :
                new ObjectParameter("currentPage", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetQuestion_Result1>("SP_GetQuestion", currentPageParameter, pageSizeParameter, productIdParameter);
        }
    
        public virtual ObjectResult<SP_GetSubQuestion_Result1> SP_GetSubQuestion(Nullable<int> questionID)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("questionID", questionID) :
                new ObjectParameter("questionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSubQuestion_Result1>("SP_GetSubQuestion", questionIDParameter);
        }
    
        public virtual int SP_UpdateQuestion(Nullable<int> questionID, string question)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("questionID", questionID) :
                new ObjectParameter("questionID", typeof(int));
    
            var questionParameter = question != null ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateQuestion", questionIDParameter, questionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetQuestionCount(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetQuestionCount", productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> SP_GetRatingProduct(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("SP_GetRatingProduct", productIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CheckRating(Nullable<int> accId, Nullable<int> productID, Nullable<int> colorId, Nullable<int> sizeId, Nullable<int> orderId)
        {
            var accIdParameter = accId.HasValue ?
                new ObjectParameter("accId", accId) :
                new ObjectParameter("accId", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(int));
    
            var colorIdParameter = colorId.HasValue ?
                new ObjectParameter("colorId", colorId) :
                new ObjectParameter("colorId", typeof(int));
    
            var sizeIdParameter = sizeId.HasValue ?
                new ObjectParameter("sizeId", sizeId) :
                new ObjectParameter("sizeId", typeof(int));
    
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("orderId", orderId) :
                new ObjectParameter("orderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CheckRating", accIdParameter, productIDParameter, colorIdParameter, sizeIdParameter, orderIdParameter);
        }
    
        public virtual ObjectResult<SP_GetRatingDetail_Result> SP_GetRatingDetail(Nullable<int> ratingId)
        {
            var ratingIdParameter = ratingId.HasValue ?
                new ObjectParameter("ratingId", ratingId) :
                new ObjectParameter("ratingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRatingDetail_Result>("SP_GetRatingDetail", ratingIdParameter);
        }
    
        public virtual ObjectResult<SP_GetShopInfo_Result> SP_GetShopInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetShopInfo_Result>("SP_GetShopInfo");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Login_Admin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Login_Admin", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<SPGetAccountInfoUserIDEmployee_Result> SPGetAccountInfoUserIDEmployee(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPGetAccountInfoUserIDEmployee_Result>("SPGetAccountInfoUserIDEmployee", userIdParameter);
        }
    }
}
