//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public string imageUrl { get; set; }
        public Nullable<int> idAccount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
