//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPromotion
    {
        public int idProduct { get; set; }
        public int idPromotion { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
