//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int idNoti { get; set; }
        public string contentNoti { get; set; }
        public Nullable<System.DateTime> dateNoti { get; set; }
        public Nullable<int> isAdmin { get; set; }
    }
}
