//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    
    public partial class SP_GetQuestion_Result1
    {
        public int questionID { get; set; }
        public Nullable<int> accountID { get; set; }
        public string username { get; set; }
        public Nullable<int> roleId { get; set; }
        public string question { get; set; }
        public Nullable<System.DateTime> dateComment { get; set; }
        public Nullable<System.DateTime> dateEdit { get; set; }
        public Nullable<int> parentQuestionID { get; set; }
    }
}
