//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    
    public partial class SP_GetRatings_Result3
    {
        public int ratingID { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateRating { get; set; }
        public Nullable<System.DateTime> dateEdit { get; set; }
        public Nullable<int> productID { get; set; }
        public string imageUrl1 { get; set; }
        public string imageUrl2 { get; set; }
        public string imageUrl3 { get; set; }
        public string videoUrl { get; set; }
        public Nullable<int> parentId { get; set; }
    }
}
