//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesManamentDataAccess
{
    using System;
    
    public partial class SP_GetProductInvoice_Result1
    {
        public int id { get; set; }
        public string title { get; set; }
        public string sizeName { get; set; }
        public string colorName { get; set; }
        public string colorHex { get; set; }
        public string detail { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<int> quantity { get; set; }
        public string thumnail { get; set; }
    }
}
