//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesAdmin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Drawing;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public string imageUrl { get; set; }
        public string thumnail { get; set; }
        public Nullable<byte> sex { get; set; }
        public Nullable<int> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [NotMapped]
        public System.Drawing.Image image
        {
            get
            {
                if (!String.IsNullOrEmpty(imageUrl))
                {
                    using (System.Net.WebClient webClient = new System.Net.WebClient())
                    {
                        using (Stream stream = webClient.OpenRead(imageUrl))
                        {
                            return System.Drawing.Image.FromStream(stream);
                        }
                    }
                }
                else return null;
            }
        }

        [NotMapped]
        public System.Drawing.Image thumbnaill
        {
            get
            {
                if (!String.IsNullOrEmpty(imageUrl))
                {
                    using (System.Net.WebClient webClient = new System.Net.WebClient())
                    {
                        using (Stream stream = webClient.OpenRead(imageUrl))
                        {
                            return System.Drawing.Image.FromStream(stream);
                        }
                    }
                }
                else return null;
            }
        }

    }
}
